version: "2"
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - decorder
    - dogsled
    - dupword
    - err113
    - errcheck
    - exhaustive
    - gocheckcompilerdirectives
    - gocritic
    - godot
    - goheader
    - gosec
    - govet
    - grouper
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    - misspell
    - noctx
    - nosprintfhostport
    - perfsprint
    - predeclared
    - revive
    - staticcheck
    - testifylint
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    gocritic:
      disabled-checks:
        - appendAssign
        - ifElseChain
        - singleCaseSwitch
    gosec:
      excludes:
        - G108 # Profiling endpoint is automatically exposed
        - G114 # ListenAndServe is used for internal APIs only
        - G401 # Use of weak cryptographic primitive
        - G404 # Use of weak random number generator
        - G501 # Blocklisted import crypto/md5
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      # It's complaining about InsecureSkipVerify being set to true, but we are
      # setting it to true intentionally if the host is localhost.
      - path: pkg/database/database.go
        text: G402 # Checking for InsecureSkipVerify
      # Ignore a bunch of linters for test files.
      - linters:
          - err113
          - errcheck
          - gosec
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
