export const LANGUAGES: { tag: string; name: string }[] = [
  { tag: "aa", name: "Afar" },
  { tag: "ab", name: "Abkhazian" },
  { tag: "ae", name: "Avestan" },
  { tag: "af", name: "Afrikaans" },
  { tag: "ak", name: "Akan" },
  { tag: "am", name: "Amharic" },
  { tag: "an", name: "Aragonese" },
  { tag: "ar", name: "Arabic" },
  { tag: "as", name: "Assamese" },
  { tag: "av", name: "Avaric" },
  { tag: "ay", name: "Aymara" },
  { tag: "az", name: "Azerbaijani" },
  { tag: "ba", name: "Bashkir" },
  { tag: "be", name: "Belarusian" },
  { tag: "bg", name: "Bulgarian" },
  { tag: "bh", name: "Bihari languages" },
  { tag: "bi", name: "Bislama" },
  { tag: "bm", name: "Bambara" },
  { tag: "bn", name: "Bengali" },
  { tag: "bo", name: "Tibetan" },
  { tag: "br", name: "Breton" },
  { tag: "bs", name: "Bosnian" },
  { tag: "ca", name: "Catalan" },
  { tag: "ce", name: "Chechen" },
  { tag: "ch", name: "Chamorro" },
  { tag: "co", name: "Corsican" },
  { tag: "cr", name: "Cree" },
  { tag: "cs", name: "Czech" },
  { tag: "cu", name: "Church Slavic" },
  { tag: "cv", name: "Chuvash" },
  { tag: "cy", name: "Welsh" },
  { tag: "da", name: "Danish" },
  { tag: "de", name: "German" },
  { tag: "de-AT", name: "German - Austria" },
  { tag: "de-CH", name: "German - Switzerland" },
  { tag: "dv", name: "Divehi" },
  { tag: "dz", name: "Dzongkha" },
  { tag: "ee", name: "Ewe" },
  { tag: "el", name: "Greek" },
  { tag: "en", name: "English" },
  { tag: "en-GB", name: "English - United Kingdom" },
  { tag: "en-US", name: "English - United States" },
  { tag: "eo", name: "Esperanto" },
  { tag: "es", name: "Spanish" },
  { tag: "es-419", name: "Spanish - Latin America" },
  { tag: "et", name: "Estonian" },
  { tag: "eu", name: "Basque" },
  { tag: "fa", name: "Persian" },
  { tag: "ff", name: "Fulah" },
  { tag: "fi", name: "Finnish" },
  { tag: "fj", name: "Fijian" },
  { tag: "fo", name: "Faroese" },
  { tag: "fr", name: "French" },
  { tag: "fr-CA", name: "French - Canada" },
  { tag: "fy", name: "Western Frisian" },
  { tag: "ga", name: "Irish" },
  { tag: "gd", name: "Scottish Gaelic" },
  { tag: "gl", name: "Galician" },
  { tag: "gn", name: "Guarani" },
  { tag: "gu", name: "Gujarati" },
  { tag: "gv", name: "Manx" },
  { tag: "ha", name: "Hausa" },
  { tag: "he", name: "Hebrew" },
  { tag: "hi", name: "Hindi" },
  { tag: "ho", name: "Hiri Motu" },
  { tag: "hr", name: "Croatian" },
  { tag: "ht", name: "Haitian Creole" },
  { tag: "hu", name: "Hungarian" },
  { tag: "hy", name: "Armenian" },
  { tag: "hz", name: "Herero" },
  { tag: "ia", name: "Interlingua" },
  { tag: "id", name: "Indonesian" },
  { tag: "ie", name: "Interlingue" },
  { tag: "ig", name: "Igbo" },
  { tag: "ii", name: "Sichuan Yi" },
  { tag: "ik", name: "Inupiaq" },
  { tag: "io", name: "Ido" },
  { tag: "is", name: "Icelandic" },
  { tag: "it", name: "Italian" },
  { tag: "iu", name: "Inuktitut" },
  { tag: "ja", name: "Japanese" },
  { tag: "jv", name: "Javanese" },
  { tag: "ka", name: "Georgian" },
  { tag: "kg", name: "Kongo" },
  { tag: "ki", name: "Kikuyu" },
  { tag: "kj", name: "Kwanyama" },
  { tag: "kk", name: "Kazakh" },
  { tag: "kl", name: "Kalaallisut" },
  { tag: "km", name: "Khmer" },
  { tag: "kn", name: "Kannada" },
  { tag: "ko", name: "Korean" },
  { tag: "kr", name: "Kanuri" },
  { tag: "ks", name: "Kashmiri" },
  { tag: "ku", name: "Kurdish" },
  { tag: "kv", name: "Komi" },
  { tag: "kw", name: "Cornish" },
  { tag: "ky", name: "Kyrgyz" },
  { tag: "la", name: "Latin" },
  { tag: "lb", name: "Luxembourgish" },
  { tag: "lg", name: "Ganda" },
  { tag: "li", name: "Limburgish" },
  { tag: "ln", name: "Lingala" },
  { tag: "lo", name: "Lao" },
  { tag: "lt", name: "Lithuanian" },
  { tag: "lu", name: "Luba-Katanga" },
  { tag: "lv", name: "Latvian" },
  { tag: "mg", name: "Malagasy" },
  { tag: "mh", name: "Marshallese" },
  { tag: "mi", name: "Maori" },
  { tag: "mk", name: "Macedonian" },
  { tag: "ml", name: "Malayalam" },
  { tag: "mn", name: "Mongolian" },
  { tag: "mr", name: "Marathi" },
  { tag: "ms", name: "Malay" },
  { tag: "mt", name: "Maltese" },
  { tag: "my", name: "Burmese" },
  { tag: "na", name: "Nauru" },
  { tag: "nb", name: "Norwegian Bokmål" },
  { tag: "nd", name: "North Ndebele" },
  { tag: "ne", name: "Nepali" },
  { tag: "ng", name: "Ndonga" },
  { tag: "nl", name: "Dutch" },
  { tag: "nn", name: "Norwegian Nynorsk" },
  { tag: "no", name: "Norwegian" },
  { tag: "nr", name: "South Ndebele" },
  { tag: "nv", name: "Navajo" },
  { tag: "ny", name: "Nyanja" },
  { tag: "oc", name: "Occitan" },
  { tag: "oj", name: "Ojibwe" },
  { tag: "om", name: "Oromo" },
  { tag: "or", name: "Odia" },
  { tag: "os", name: "Ossetic" },
  { tag: "pa", name: "Punjabi" },
  { tag: "pi", name: "Pali" },
  { tag: "pl", name: "Polish" },
  { tag: "ps", name: "Pashto" },
  { tag: "pt", name: "Portuguese" },
  { tag: "pt-BR", name: "Portuguese - Brazil" },
  { tag: "pt-PT", name: "Portuguese - Portugal" },
  { tag: "qu", name: "Quechua" },
  { tag: "rm", name: "Romansh" },
  { tag: "rn", name: "Rundi" },
  { tag: "ro", name: "Romanian" },
  { tag: "ru", name: "Russian" },
  { tag: "rw", name: "Kinyarwanda" },
  { tag: "sa", name: "Sanskrit" },
  { tag: "sc", name: "Sardinian" },
  { tag: "sd", name: "Sindhi" },
  { tag: "se", name: "Northern Sami" },
  { tag: "sg", name: "Sango" },
  { tag: "si", name: "Sinhala" },
  { tag: "sk", name: "Slovak" },
  { tag: "sl", name: "Slovenian" },
  { tag: "sm", name: "Samoan" },
  { tag: "sn", name: "Shona" },
  { tag: "so", name: "Somali" },
  { tag: "sq", name: "Albanian" },
  { tag: "sr", name: "Serbian" },
  { tag: "sr-Cyrl", name: "Serbian - Cyrillic" },
  { tag: "sr-Latn", name: "Serbian - Latin" },
  { tag: "ss", name: "Swati" },
  { tag: "st", name: "Southern Sotho" },
  { tag: "su", name: "Sundanese" },
  { tag: "sv", name: "Swedish" },
  { tag: "sw", name: "Swahili" },
  { tag: "ta", name: "Tamil" },
  { tag: "te", name: "Telugu" },
  { tag: "tg", name: "Tajik" },
  { tag: "th", name: "Thai" },
  { tag: "ti", name: "Tigrinya" },
  { tag: "tk", name: "Turkmen" },
  { tag: "tl", name: "Filipino" },
  { tag: "tn", name: "Tswana" },
  { tag: "to", name: "Tongan" },
  { tag: "tr", name: "Turkish" },
  { tag: "ts", name: "Tsonga" },
  { tag: "tt", name: "Tatar" },
  { tag: "tw", name: "Twi" },
  { tag: "ty", name: "Tahitian" },
  { tag: "ug", name: "Uyghur" },
  { tag: "uk", name: "Ukrainian" },
  { tag: "ur", name: "Urdu" },
  { tag: "uz", name: "Uzbek" },
  { tag: "ca-valencia", name: "Valencian" },
  { tag: "ve", name: "Venda" },
  { tag: "vi", name: "Vietnamese" },
  { tag: "vo", name: "Volapük" },
  { tag: "wa", name: "Walloon" },
  { tag: "wo", name: "Wolof" },
  { tag: "xh", name: "Xhosa" },
  { tag: "yi", name: "Yiddish" },
  { tag: "yo", name: "Yoruba" },
  { tag: "za", name: "Zhuang" },
  { tag: "zh", name: "Chinese" },
  { tag: "zh-Hans", name: "Chinese - Simplified" },
  { tag: "zh-Hant", name: "Chinese - Traditional" },
  { tag: "zu", name: "Zulu" },
].sort((a, b) => a.name.localeCompare(b.name));

export function getLanguageName(tag: string): string | undefined {
  return LANGUAGES.find((l) => l.tag === tag)?.name;
}
