import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This file alone sets the order; never rely on sidebar_position,
// category metadata, filesystem order, or an autogenerated sidebar. Place a
// new page where its reader would look for it, never at the bottom by
// default. Using Shisho starts expanded because it holds daily tasks.
// Troubleshooting stays top-level because urgent problems cross categories,
// and Developer stays last.
//
// Every page in docs/ is either placed below or listed in legacyDocs.ts, the
// legacy fragments left out on purpose; sidebars.test.ts fails otherwise.
// Keep this file's only export the default: Docusaurus would read a named
// export as another sidebar.
const sidebars: SidebarsConfig = {
  docsSidebar: [
    "getting-started",
    "demo",
    "supported-formats",
    {
      type: "category",
      label: "Using Shisho",
      collapsed: false,
      items: [
        "browsing-search-bulk-actions",
        "reading-and-playback",
        "managing-books-and-files",
        "metadata",
        "lists",
        "sharing",
      ],
    },
    {
      type: "category",
      label: "Administration",
      collapsed: true,
      items: [
        "deployment-and-maintenance",
        "configuration",
        "libraries",
        "users-and-permissions",
        "plugins/overview",
        "supplement-files",
        "sidecar-files",
      ],
    },
    {
      type: "category",
      label: "Integrations",
      collapsed: true,
      items: ["opds", "kobo-sync", "ereader-browser"],
    },
    "troubleshooting",
    {
      type: "category",
      label: "Developer",
      collapsed: true,
      items: [
        "plugins/development",
        "plugins/manifest-hooks-reference",
        "plugins/host-api-reference",
        "plugins/testing",
        "plugins/publishing",
      ],
    },
  ],
};

export default sidebars;
